### ISSUE TITLE
confusing message setting up params - SpaDES.core is installed

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.project#27] opened 2023-02-25 06:24 UTC
```r
setting up params...
Skipping checking of parameters supplied against module parameters because SpaDES.core is not installed. Please install if this check is desired.
```

but the package is installed:

```r
> packageVersion("SpaDES.core")
[1] ‘1.1.1’
```

<details closed>

```r
> needPkgs <- list(
+   reproducible =  "PredictiveEcology/reproducible@development (>= 1.2.16.9017)",
+   SpaDES.core = "PredictiveEcology/SpaDES.core@development (>= 1.1.1)",
+   SpaDES.project = "PredictiveEcology/SpaDES.project@23-gitignore (>= 0.0.7.9021)"
+ )
> 
> ## WORKAROUND SpaDES.project failures to install packages correctly
> while (!require("Require", quietly = TRUE)) {
+   ## will install latest development version from PE r-universe
+   install.packages("Require", lib = pkgDir)
+   require("Require", lib.loc = pkgDir)
+ }
> 
> while (!require("SpaDES.core", quietly = TRUE)) {
+   Require::Install(needPkgs$SpaDES.core)
+ }
> ## END WORKAROUND
> 
> while (!require("SpaDES.project", quietly = TRUE)) {
>   ## TODO: PE r-universe tracks development; need diff branch
+   # install.packages("SpaDES.project", repos = "https://predictiveecology.r-universe.dev")
+   # require(SpaDES.project)
+ 
+   Require::Install(needPkgs$SpaDES.project)
+ }
> 
> out <- SpaDES.project::setupProject(
+   paths = list(projectPath = prjDir,
+                packagePath = pkgDir,
+                modulePath = "modules",
+                inputPath = "inputs",
+                outputPath = "outputs"),
+   packages = c(
+     "PredictiveEcology/CBMutils@development (>= 0.0.7.9009)", ## TODO: this should be pulled in via modules already
+     "googledrive",
+     "PredictiveEcology/Require@development (>= 0.2.6)",
+     "rgdal", "sf", ## TODO: why is Require trying to install binary versions?? not using RSPM!
+     needPkgs$SpaDES.core
+   ),
+   require = c(
+     needPkgs$reproducible,
+     needPkgs$SpaDES.core
+   ),
+   modules = c("PredictiveEcology/CBM_defaults@main",
+               "PredictiveEcology/CBM_dataPrep_SK@development",
+               "PredictiveEcology/CBM_vol2biomass@CBM_vol2biomass_SK",
+               "PredictiveEcology/CBM_core@main"),
+   params = list(
+     CBM_defaults = list(
+       .useCache = TRUE
+     ),
+     CBM_dataPrep_SK = list(
+       .useCache = TRUE
+     ),
+     CBM_vol2biomass = list(
+       outputFigurePath = switch(.user,
+                                 achubaty = file.path("outputs", "figures", "CBM_vol2biomass"),
+                                 NA), ## NA means use default: './modules/CBM_vol2biomass/figures/'
+       .useCache = TRUE
+     ),
+     CBM_core = list(
+       #.useCache = "init", #c(".inputObjects", "init")
+       .plotInterval = 1,
+       .plotInitialTime = 1990,
+       poolsToPlot = c("totalCarbon"),
+       spinupDebug = FALSE ## TODO: temporary
+     )
+   ),
+   options = list(
+     reproducible.destinationPath = if (.user == "cboisven") NULL else "inputs", ## TODO: SpaDES.project#24
+     reproducible.useTerra = TRUE
+   ),
+   times = list(start = 1990.00, end = 1993.00),
+   setLinuxBinaryRepo = FALSE, ## TODO: interferes with other package installation
+   updateRprofile  = FALSE ## TODO: verify what it is doing
+ )
setting up paths ...
Setting:
  options(
    reproducible.cachePath = '/home/achubaty/Documents/GitHub/spadesCBM/cache'
    spades.inputPath = '/mnt/projects/CBM/spadesCBM/inputs'
    spades.outputPath = '/mnt/projects/CBM/spadesCBM/outputs'
    spades.modulePath = '/home/achubaty/Documents/GitHub/spadesCBM/modules'
    spades.scratchPath = '/tmp/Rtmp3SCBUF/SpaDES.project/spadesCBM'
  )
  done setting up paths
setting up options...
The following options have been changed
                     optionName newValue oldValue
1: reproducible.destinationPath   inputs         
2:        reproducible.useTerra     TRUE    FALSE
setting up modules
                                                modules    downloaded                                        modulePath
1:                  PredictiveEcology/CBM_defaults@main already local /home/achubaty/Documents/GitHub/spadesCBM/modules
2:        PredictiveEcology/CBM_dataPrep_SK@development already local /home/achubaty/Documents/GitHub/spadesCBM/modules
3: PredictiveEcology/CBM_vol2biomass@CBM_vol2biomass_SK already local /home/achubaty/Documents/GitHub/spadesCBM/modules
4:                      PredictiveEcology/CBM_core@main already local /home/achubaty/Documents/GitHub/spadesCBM/modules
setting up packages...
Installing any missing reqdPkgs Done!
  done setting up packages
.libPaths() are: /home/achubaty/.local/share/R/spadesCBM/packages/x86_64-pc-linux-gnu/4.2, /usr/lib/R/library
setting up params...
Skipping checking of parameters supplied against module parameters because SpaDES.core is not installed. Please install if this check is desired.
  done setting up params
Option 'SpaDES.project.updateGitIgnore' is FALSE. No changes were made to .gitignore.
```

</details>
<br>

**Comment by eliotmcintire** [comment] 2023-02-25 06:51
You can't install `Require` or any of the `SpaDES.project` dependencies within `SpaDES.project`. Similarly, since SpaDES.project has Require as a dependency, you don't need to install `Require` directly.

I have found this option to work as the first line in a script:
```
if (tryCatch(packageVersion("SpaDES.project") < "0.0.7.9020", error = function(e) TRUE)) {
  install.packages("SpaDES.project",
                   repos = c("https://predictiveecology.r-universe.dev",
                             getOption("repos")))
}
```
I don't have a failure with your reprex, so I can't suggest anything to stop using the work arounds. There are several variables that I don't have access to (e.g., pkgDir, prjDir), so I can't try to understand why something very similar to this code works for me on 2 OSs and several computers. 

If you need hotter of the press version, this works, but obviously need `Require`, so that would have to be added... though if you are hot off the press, you can probably assume that `Require` is installed.
```
if (tryCatch(packageVersion("SpaDES.project") < "0.0.7.9020", error = function(e) TRUE)) {
  system.time(Require::Install("PredictiveEcology/SpaDES.project@transition (HEAD)"))
}
```

**Comment by eliotmcintire** [comment] 2023-02-25 06:54
I don't know what your `.libPaths()` are doing. Most likely you are installing `SpaDES.core` to one path and it is being searched for in another.

When you try to give a reprex, it is a lot easier if all the variables are identified, and also, please don't post the print out returned by the R console; rather, provide the actual code that is submitted to the R console (i.e., so can just copy and paste it).

**Comment by eliotmcintire** [comment] 2023-02-25 07:17
I run this chunk and it works all as expected. The slight changes I have made are 1) remove the prjDir and pkgDir (I didn't have them), 2) don't try to install `Require`, 3) don't need `sf` as it is requested by modules, unname the `require = ` arg entries and 4) didn't do the workaround stuff including the different branch of `Require`, 5) you can't use `Require` to install `SpaDES.project` unless `Require` is already installed, as it is a dependency, so I use the `install.packages`. 

I didn't get the warning/message... 

```
if (tryCatch(packageVersion("SpaDES.project") < "0.0.7.9020", error = function(e) TRUE)) {
  install.packages("SpaDES.project",
                   repos = c("https://predictiveecology.r-universe.dev",
                             getOption("repos")))
}
out <- SpaDES.project::setupProject(
  paths = list(#projectPath = prjDir,
               #packagePath = pkgDir,
               modulePath = "modules",
               inputPath = "inputs",
               outputPath = "outputs"),
  packages = c(
    "PredictiveEcology/CBMutils@development (>= 0.0.7.9009)", ## TODO: this should be pulled in via modules already
    "googledrive",
    "rgdal"#, "sf" ## TODO: why is Require trying to install binary versions?? not using RSPM!
  ),
  require = c(
     "PredictiveEcology/reproducible@development (>= 1.2.16.9017)",
     "PredictiveEcology/SpaDES.core@development (>= 1.1.1)"
  ),
  modules = c("PredictiveEcology/CBM_defaults@main",
              "PredictiveEcology/CBM_dataPrep_SK@development",
              "PredictiveEcology/CBM_vol2biomass@CBM_vol2biomass_SK",
              "PredictiveEcology/CBM_core@main"),
  params = list(
    CBM_defaults = list(
      .useCache = TRUE
    ),
    CBM_dataPrep_SK = list(
      .useCache = TRUE
    ),
    CBM_vol2biomass = list(
      outputFigurePath = switch(user(),
                                achubaty = file.path("outputs", "figures", "CBM_vol2biomass"),
                                NA), ## NA means use default: './modules/CBM_vol2biomass/figures/'
      .useCache = TRUE
    ),
    CBM_core = list(
      #.useCache = "init", #c(".inputObjects", "init")
      .plotInterval = 1,
      .plotInitialTime = 1990,
      poolsToPlot = c("totalCarbon"),
      spinupDebug = FALSE ## TODO: temporary
    )
  ),
  options = list(
    reproducible.destinationPath = if (user() == "cboisven") NULL else "inputs", ## TODO: SpaDES.project#24
    reproducible.useTerra = TRUE
  ),
  times = list(start = 1990.00, end = 1993.00),
  setLinuxBinaryRepo = FALSE, ## TODO: interferes with other package installation
  updateRprofile  = FALSE ## TODO: verify what it is doing
)
```

If you can provide a reprex, I may be able to help debug.

**Comment by achubaty** [comment] 2023-02-25 07:40
I'm trying to use the existing setupProject() for spadesCBM. Full code here: https://github.com/cboisvenue/spadesCBM/blob/amc/new_libCBMGlobal.R

Trying to running on Ubuntu 20.04 and macOS Big Sur (macOS sees a whole other set of failures). I am using the most recent SpaDES.project (you'll see I'm using the branch with the PR that implements #23).

>  run this chunk and it works all as expected. The slight changes I have made are:
> 1) remove the prjDir and pkgDir (I didn't have them)

these shouldn't matter but they are:

```r
prjDir <- "~/GitHub/spadesCBM"
pkgDir <- file.path(tools::R_user_dir(basename(prjDir), "data"), "packages",
                    version$platform, getRversion()[, 1:2])
```

> 2) don't try to install Require

It fails to install things correctly, but manually installing things one at a time seems to mostly work. As mentioned above, I am trying to use existing code.

> 3) don't need sf as it is requested by modules

the latest development version (v1.0.10) is not specified by the modules -- this includes important z-coord error fixes for windows. compiling `sf` this for Windows generally fails, so I am grabbing the prebuilt binary fro the r-spatial repo.

> unname the require =  arg entries 

Sorry, I don't understand - they aren't named:

```r
> c(
+     needPkgs$reproducible,
+     needPkgs$SpaDES.core
+   )
[1] "PredictiveEcology/reproducible@development (>= 1.2.16.9017)" "PredictiveEcology/SpaDES.core@development (>= 1.1.1)"     
```

> 4) didn't do the workaround stuff including the different branch of Require

do you mean different branch of `SpaDES.project`? that's essential to prevent .gitignore problems.

> 5) you can't use Require to install SpaDES.project unless Require is already installed, as it is a dependency, so I use the install.packages.

In 2) above you say not to install `Require`, but I did, and it should be available. `install.packages` cannot install GitHub packages (with 4) above)

> 6) paths are all defaults, so I omit them.

should make no difference then

> 7) remove the CBMutils@development install; it happens due to modules

It's supposed to yes (and it's flagged for removal). I am trying to run existing projectSetup() with zero/minimal changes. The only workarounds I can do need to be outside of the setupProject() call.

**Comment by eliotmcintire** [comment] 2023-02-25 07:46
So, maybe your computer just doesn't work with SpaDES.project. Everything works for me and you can't help me to reproduce your problems. 

Everything worked for me. I tried 3 different starting conditions. All the CBM example works for me and Celine (I helped her build it). 

I didn't have any `.gitignore` problems, so your branch was not necessary. 

Sorry. 

Shall we close this issue or do you want it to so you can work on it yourself?

**Comment by achubaty** [comment] 2023-02-25 07:51
I'm happy to provide further details and show you the behaviour on my machines. Even if I take more time to implement fixes for all of these myself, they still require coordination and review by you.

**Comment by eliotmcintire** [comment] 2023-03-06 20:49
Back to the **title** of this issue. The particular message was part of "in progress", so it was part of an `if (FALSE) {  } else { "SpaDES.core is not installed"}.

So, it has been removed now.

**Closed by eliotmcintire** 2023-03-06 20:49 UTC
